# Generated by Django 4.0.3 on 2022-03-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('developer', models.CharField(max_length=300)),
                ('created_date', models.DateField()),
                ('averangeRating', models.FloatField()),
            ],
        ),
    ]
