# Generated by Django 4.0.3 on 2022-03-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='linktosite',
            field=models.URLField(default=None, null=True),
        ),
    ]
