# Generated by Django 4.0.3 on 2022-03-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_award_image_award_linktosite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='averangeRating',
            field=models.FloatField(default=0),
        ),
    ]
